In [1]:
import openpyxl
from openpyxl.worksheet.table import Table, TableStyleInfo
import numpy as np
import pandas as pd
import sqlalchemy
from datetime import datetime
import psycopg2
from sqlalchemy import create_engine
import pandas.io.sql as psql
import os
import re

In [2]:
# READ DATA FROM POSTGRESQL FOR MEASUREMENT RESULTS

conn = psycopg2.connect(database="Fiches", user="postgres", password="Narnia2011", host="localhost", port="5432")
cur = conn.cursor()
df_measurement_results = psql.read_sql("Select * from clean_df_measurement_results_field", conn)
df_measurement_results = pd.DataFrame(data = df_measurement_results, index=None)

# READ DATA FROM POSTGRESQL FOR SWITCH CHARACTERISTICS

conn = psycopg2.connect(database="Fiches", user="postgres", password="Narnia2011", host="localhost", port="5432")
cur = conn.cursor()
df_switch_characteristics = psql.read_sql("Select * from clean_switch_characteristics_field", conn)
df_switch_characteristics = pd.DataFrame(data = df_switch_characteristics, index=None)

# READ DATA FROM POSTGRESQL FOR control infos
df_control_infos = psql.read_sql("Select * from clean_control_infos_field", conn)
df_control_infos = pd.DataFrame(data = df_control_infos, index=None)


df_control_infos['Section'] = df_control_infos['Section'].astype(int)
df_measurement_results['Section'] = df_measurement_results['Section'].astype(int)
df_switch_characteristics['Section'] = df_switch_characteristics['Section'].astype(int)

merged_df = pd.merge(df_control_infos, df_measurement_results, on='Section', how='outer')

final_merged_df = pd.merge(merged_df, df_switch_characteristics, on='Section', how='outer')

final_merged_df = final_merged_df[['No. Ident.','Numéro ES','Quote_name','Quote_measured_value','Corrected_value','Nominal_value','IAL_min','IAL_max','IL_min','IL_max','AL_min','AL_max','NEW_min','NEW_max','MAI_min','MAI_max','Quote_category',	'Quote_State','Branch', 'Quote_name_general','Date de contrôle','Date dernier contrôle','Type de contrôle','Règle 1','Périodicité','Fiche remplie par:','Catégorie UIC','Stratégie',"Type d'appareil","Switch_family",'Tangent_hart','Déviation','Vitesse branche directe','Vitesse branche déviée','Faisceau','Date dernier renouv.','Coeur(s) fissuré(s)','Gare / Bifurcation','Ligne','Catégorie de voie','Voie','Wissel_begin','Wisselzone_begin','Wissel_einde','Wisselzone_einde','Wissel_begin_KP','Wissel_begin_M','Wissel_einde_KP','Wissel_einde_M','Wisselzone_begin_KP','Wisselzone_begin_M','Wisselzone_einde_KP','Wisselzone_einde_M','Modèle coeur P1','Modèle coeur P2',"Nombre d'attaques compl.",'Rayon voie directe','Straal_afwijkende_tak','Nominale verkanting','Model halve tongenstellen','Modèle coeur K1/K2','Arrond.:','Poste:','Switch_familyyy','Section']]
final_merged_df

C:\Users\SBX9900\AppData\Local\Temp\ipykernel_17604\320249218.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_measurement_results = psql.read_sql("Select * from clean_df_measurement_results_field", conn)
C:\Users\SBX9900\AppData\Local\Temp\ipykernel_17604\320249218.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_switch_characteristics = psql.read_sql("Select * from clean_switch_characteristics_field", conn)
C:\Users\SBX9900\AppData\Local\Temp\ipykernel_17604\320249218.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_control_infos = psql.read_sql("Select * from clean_control_infos_field", conn)

,No. Ident.,Numéro ES,Quote_name,Quote_measured_value,Corrected_value,Nominal_value,IAL_min,IAL_max,IL_min,IL_max,...,Nombre d'attaques compl.,Rayon voie directe,Straal_afwijkende_tak,Nominale verkanting,Model halve tongenstellen,Modèle coeur K1/K2,Arrond.:,Poste:,Switch_familyyy,Section
0,00886,608,1E1,1434.7,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
1,00886,608,1E2,1439.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
2,00886,608,1E3,1434.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
3,00886,608,1J1,1,None,,5,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
4,00886,608,1G1,74.1,None,,,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941523,17218,28AL/25BL,2K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941524,17218,28AL/25BL,3K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941525,17218,28AL/25BL,3K2,7,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941526,17218,28AL/25BL,4K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941527,17218,28AL/25BL,4K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026

In [3]:
# READ DATA FROM POSTGRESQL FOR SWITCH CHARACTERISTICS

conn = psycopg2.connect(database="Fiches", user="postgres", password="Narnia2011", host="localhost", port="5432")
cur = conn.cursor()
df_switch_characteristics = psql.read_sql("Select * from clean_switch_characteristics_field", conn)
df_switch_characteristics = pd.DataFrame(data = df_switch_characteristics, index=None)

# READ DATA FROM POSTGRESQL FOR control infos
df_control_infos = psql.read_sql("Select * from clean_control_infos_field", conn)
df_control_infos = pd.DataFrame(data = df_control_infos, index=None)


df_control_infos['Section'] = df_control_infos['Section'].astype(int)
df_measurement_results['Section'] = df_measurement_results['Section'].astype(int)
df_switch_characteristics['Section'] = df_switch_characteristics['Section'].astype(int)

merged_df = pd.merge(df_control_infos, df_measurement_results, on='Section', how='outer')

final_merged_df = pd.merge(merged_df, df_switch_characteristics, on='Section', how='outer')

final_merged_df = final_merged_df[['No. Ident.','Numéro ES','Quote_name','Quote_measured_value','Corrected_value','Nominal_value','IAL_min','IAL_max','IL_min','IL_max','AL_min','AL_max','NEW_min','NEW_max','MAI_min','MAI_max','Quote_category',	'Quote_State','Branch', 'Quote_name_general','Date de contrôle','Date dernier contrôle','Type de contrôle','Règle 1','Périodicité','Fiche remplie par:','Catégorie UIC','Stratégie',"Type d'appareil","Switch_family",'Tangent_hart','Déviation','Vitesse branche directe','Vitesse branche déviée','Faisceau','Date dernier renouv.','Coeur(s) fissuré(s)','Gare / Bifurcation','Ligne','Catégorie de voie','Voie','Wissel_begin','Wisselzone_begin','Wissel_einde','Wisselzone_einde','Wissel_begin_KP','Wissel_begin_M','Wissel_einde_KP','Wissel_einde_M','Wisselzone_begin_KP','Wisselzone_begin_M','Wisselzone_einde_KP','Wisselzone_einde_M','Modèle coeur P1','Modèle coeur P2',"Nombre d'attaques compl.",'Rayon voie directe','Straal_afwijkende_tak','Nominale verkanting','Model halve tongenstellen','Modèle coeur K1/K2','Arrond.:','Poste:','Switch_familyyy','Section']]
final_merged_df

C:\Users\SBX9900\AppData\Local\Temp\ipykernel_17604\3513534000.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_switch_characteristics = psql.read_sql("Select * from clean_switch_characteristics_field", conn)
C:\Users\SBX9900\AppData\Local\Temp\ipykernel_17604\3513534000.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_control_infos = psql.read_sql("Select * from clean_control_infos_field", conn)

,No. Ident.,Numéro ES,Quote_name,Quote_measured_value,Corrected_value,Nominal_value,IAL_min,IAL_max,IL_min,IL_max,...,Nombre d'attaques compl.,Rayon voie directe,Straal_afwijkende_tak,Nominale verkanting,Model halve tongenstellen,Modèle coeur K1/K2,Arrond.:,Poste:,Switch_familyyy,Section
0,00886,608,1E1,1434.7,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
1,00886,608,1E2,1439.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
2,00886,608,1E3,1434.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
3,00886,608,1J1,1,None,,5,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
4,00886,608,1G1,74.1,None,,,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941523,17218,28AL/25BL,2K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941524,17218,28AL/25BL,3K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941525,17218,28AL/25BL,3K2,7,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941526,17218,28AL/25BL,4K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941527,17218,28AL/25BL,4K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026

In [4]:
# READ DATA FROM POSTGRESQL FOR control infos
df_control_infos = psql.read_sql("Select * from clean_control_infos_field", conn)
df_control_infos = pd.DataFrame(data = df_control_infos, index=None)


df_control_infos['Section'] = df_control_infos['Section'].astype(int)
df_measurement_results['Section'] = df_measurement_results['Section'].astype(int)
df_switch_characteristics['Section'] = df_switch_characteristics['Section'].astype(int)

merged_df = pd.merge(df_control_infos, df_measurement_results, on='Section', how='outer')

final_merged_df = pd.merge(merged_df, df_switch_characteristics, on='Section', how='outer')

final_merged_df = final_merged_df[['No. Ident.','Numéro ES','Quote_name','Quote_measured_value','Corrected_value','Nominal_value','IAL_min','IAL_max','IL_min','IL_max','AL_min','AL_max','NEW_min','NEW_max','MAI_min','MAI_max','Quote_category',	'Quote_State','Branch', 'Quote_name_general','Date de contrôle','Date dernier contrôle','Type de contrôle','Règle 1','Périodicité','Fiche remplie par:','Catégorie UIC','Stratégie',"Type d'appareil","Switch_family",'Tangent_hart','Déviation','Vitesse branche directe','Vitesse branche déviée','Faisceau','Date dernier renouv.','Coeur(s) fissuré(s)','Gare / Bifurcation','Ligne','Catégorie de voie','Voie','Wissel_begin','Wisselzone_begin','Wissel_einde','Wisselzone_einde','Wissel_begin_KP','Wissel_begin_M','Wissel_einde_KP','Wissel_einde_M','Wisselzone_begin_KP','Wisselzone_begin_M','Wisselzone_einde_KP','Wisselzone_einde_M','Modèle coeur P1','Modèle coeur P2',"Nombre d'attaques compl.",'Rayon voie directe','Straal_afwijkende_tak','Nominale verkanting','Model halve tongenstellen','Modèle coeur K1/K2','Arrond.:','Poste:','Switch_familyyy','Section']]
final_merged_df

C:\Users\SBX9900\AppData\Local\Temp\ipykernel_17604\1220389637.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_control_infos = psql.read_sql("Select * from clean_control_infos_field", conn)

,No. Ident.,Numéro ES,Quote_name,Quote_measured_value,Corrected_value,Nominal_value,IAL_min,IAL_max,IL_min,IL_max,...,Nombre d'attaques compl.,Rayon voie directe,Straal_afwijkende_tak,Nominale verkanting,Model halve tongenstellen,Modèle coeur K1/K2,Arrond.:,Poste:,Switch_familyyy,Section
0,00886,608,1E1,1434.7,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
1,00886,608,1E2,1439.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
2,00886,608,1E3,1434.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
3,00886,608,1J1,1,None,,5,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
4,00886,608,1G1,74.1,None,,,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941523,17218,28AL/25BL,2K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941524,17218,28AL/25BL,3K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941525,17218,28AL/25BL,3K2,7,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941526,17218,28AL/25BL,4K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941527,17218,28AL/25BL,4K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026

In [5]:
df_control_infos

,index,No. Ident.,Date de contrôle,Date dernier contrôle,Type de contrôle,Règle 1,Périodicité,Fiche remplie par:,Path,Section,Control_index
0,0,00886,20/03/2019,16/04/2018,VC,16/01415,12,,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\D...,3,1
1,1,00889,20/03/2019,16/04/2018,VC,16/01415,12,,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\D...,4,2
2,2,00900,20/03/2019,08/03/2018,UC,16/01415,12,,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\D...,5,3
3,3,01092,04/04/2019,21/09/2018,UC,16/01138,6,Dirk Defour,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\D...,11,4
4,4,01094,28/03/2019,02/04/2018,UC,16/01138,12,,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\D...,12,5
...,...,...,...,...,...,...,...,...,...,...,...
32457,32457,16221,28/07/2020,25/05/2020,UC,16/01398,6,Bechet J,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\F...,39022,32458
32458,32458,16470,22/09/2020,08/04/2020,UC,16/01400,12,Cheverier Benoit,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\F...,39023,32459
32459,32459,16965,19/05/2020,05/02/2019,UC,16/01149,6,Smolders,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\F...,39024,32460
32460,32460,17090,15/03/2010,18/05/2021,UC,16/01136,6,Ricca,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\F...,39025,32461
32461,32461,17218,15/06/2023,25/05/2020,UC,22/02281,6,Bodlet F,C:\Users\SBX9900\OneDrive - INFRABEL\Desktop\F...,39026,32462

In [6]:
df_measurement_results.columns

Index(['level_0', 'Quote_name', 'Quote_measured_value', 'Corrected_value',
       'Branch', 'Nominal_value', 'IAL_min', 'IAL_max', 'IL_min', 'IL_max',
       'AL_min', 'AL_max', 'NEW_min', 'NEW_max', 'MAI_min', 'MAI_max',
       'Quote_category', 'Quote_State', 'Section', 'index',
       'Quote_name_general'],
      dtype='object')

In [7]:
df_switch_characteristics.columns

Index(['index', 'Numéro ES', 'Catégorie UIC', 'Stratégie', 'Type d'appareil',
       'Switch_family', 'Tangent_hart', 'Déviation', 'Vitesse branche directe',
       'Vitesse branche déviée', 'Faisceau', 'Date dernier renouv.',
       'Coeur(s) fissuré(s)', 'Gare / Bifurcation', 'Ligne',
       'Catégorie de voie', 'Voie', 'Wissel_begin', 'Wisselzone_begin',
       'Wissel_einde', 'Wisselzone_einde', 'Wissel_begin_KP', 'Wissel_begin_M',
       'Wissel_einde_KP', 'Wissel_einde_M', 'Wisselzone_begin_KP',
       'Wisselzone_begin_M', 'Wisselzone_einde_KP', 'Wisselzone_einde_M',
       'Modèle coeur P1', 'Modèle coeur P2', 'Nombre d'attaques compl.',
       'Rayon voie directe', 'Straal_afwijkende_tak', 'Nominale verkanting',
       'Model halve tongenstellen', 'Modèle coeur K1/K2', 'Arrond.:', 'Poste:',
       'Section', 'Switch_index', 'Switch_familyyy'],
      dtype='object')

In [8]:
df_control_infos['Section'] = df_control_infos['Section'].astype(int)
df_measurement_results['Section'] = df_measurement_results['Section'].astype(int)
df_switch_characteristics['Section'] = df_switch_characteristics['Section'].astype(int)

merged_df = pd.merge(df_control_infos, df_measurement_results, on='Section', how='outer')

final_merged_df = pd.merge(merged_df, df_switch_characteristics, on='Section', how='outer')

final_merged_df = final_merged_df[['No. Ident.','Numéro ES','Quote_name','Quote_measured_value','Corrected_value','Nominal_value','IAL_min','IAL_max','IL_min','IL_max','AL_min','AL_max','NEW_min','NEW_max','MAI_min','MAI_max','Quote_category',	'Quote_State','Branch', 'Quote_name_general','Date de contrôle','Date dernier contrôle','Type de contrôle','Règle 1','Périodicité','Fiche remplie par:','Catégorie UIC','Stratégie',"Type d'appareil","Switch_family",'Tangent_hart','Déviation','Vitesse branche directe','Vitesse branche déviée','Faisceau','Date dernier renouv.','Coeur(s) fissuré(s)','Gare / Bifurcation','Ligne','Catégorie de voie','Voie','Wissel_begin','Wisselzone_begin','Wissel_einde','Wisselzone_einde','Wissel_begin_KP','Wissel_begin_M','Wissel_einde_KP','Wissel_einde_M','Wisselzone_begin_KP','Wisselzone_begin_M','Wisselzone_einde_KP','Wisselzone_einde_M','Modèle coeur P1','Modèle coeur P2',"Nombre d'attaques compl.",'Rayon voie directe','Straal_afwijkende_tak','Nominale verkanting','Model halve tongenstellen','Modèle coeur K1/K2','Arrond.:','Poste:','Switch_familyyy','Section']]
final_merged_df

,No. Ident.,Numéro ES,Quote_name,Quote_measured_value,Corrected_value,Nominal_value,IAL_min,IAL_max,IL_min,IL_max,...,Nombre d'attaques compl.,Rayon voie directe,Straal_afwijkende_tak,Nominale verkanting,Model halve tongenstellen,Modèle coeur K1/K2,Arrond.:,Poste:,Switch_familyyy,Section
0,00886,608,1E1,1434.7,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
1,00886,608,1E2,1439.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
2,00886,608,1E3,1434.1,None,,1424,1470,1426,1465,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
3,00886,608,1J1,1,None,,5,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
4,00886,608,1G1,74.1,None,,,,,,...,"1,0",980,298.36,40,None,None,24,2421,PX,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941523,17218,28AL/25BL,2K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941524,17218,28AL/25BL,3K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941525,17218,28AL/25BL,3K2,7,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941526,17218,28AL/25BL,4K1,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026
1941527,17218,28AL/25BL,4K2,8,None,8,3,,,,...,"0,5",None,None,None,None,None,46,4621,TJD,39026

In [31]:
pd.set_option('display.max_rows',101)
df_filtered = final_merged_df.sort_values(by=['No. Ident.', 'Quote_name', 'Date de contrôle'])
df_filtered[['No. Ident.', 'Quote_name','Quote_measured_value', 'Date de contrôle']].head(100)

       No. Ident. Quote_name Quote_measured_value Date de contrôle
800936      00004         1B               1393.5       01/03/2021
664007      00004         1B               1392.4       04/08/2020
25593       00004         1B               1393.1       15/05/2019
370320      00004         1B               1392.5       18/02/2020
224511      00004         1B               1392.2       25/09/2019
800935      00004         1C                 38.5       01/03/2021
664006      00004         1C                 39.1       04/08/2020
25592       00004         1C                 38.4       15/05/2019
370319      00004         1C                 39.6       18/02/2020
224510      00004         1C                 39.7       25/09/2019
800937      00004         1D               1348.5       01/03/2021
664008      00004         1D               1347.3       04/08/2020
25594       00004         1D               1347.9       15/05/2019
370321      00004         1D               1347.2       18/02/2020
224512      00004         1D               1346.8       25/09/2019
800925      00004        1E1               1435.5       01/03/2021
663996      00004        1E1               1435.7       04/08/2020
25582       00004        1E1               1435.2       15/05/2019
370309      00004        1E1               1435.7       18/02/2020
224500      00004        1E1               1436.2       25/09/2019
800926      00004        1E2               1436.5       01/03/2021
663997      00004        1E2               1437.3       04/08/2020
25583       00004        1E2                 1436       15/05/2019
370310      00004        1E2               1437.6       18/02/2020
224501      00004        1E2                 1437       25/09/2019
800927      00004        1E3               1434.5       01/03/2021
663998      00004        1E3               1434.6       04/08/2020
25584       00004        1E3               1435.7       15/05/2019
370311      00004        1E3               1437.6       18/02/2020
224502      00004        1E3               1435.9       25/09/2019
800931      00004        1E4                 1435       01/03/2021
664002      00004        1E4               1437.8       04/08/2020
25588       00004        1E4               1437.2       15/05/2019
370315      00004        1E4               1438.7       18/02/2020
224506      00004        1E4                 1438       25/09/2019
800932      00004        1E5                 1435       01/03/2021
664003      00004        1E5               1434.6       04/08/2020
25589       00004        1E5               1434.5       15/05/2019
370316      00004        1E5               1435.3       18/02/2020
224507      00004        1E5               1434.5       25/09/2019
800933      00004        1E6                 1434       01/03/2021
664004      00004        1E6               1433.2       04/08/2020
25590       00004        1E6               1433.1       15/05/2019
370317      00004        1E6               1434.6       18/02/2020
224508      00004        1E6               1433.7       25/09/2019
800934      00004        1E7                 1433       01/03/2021
664005      00004        1E7               1433.2       04/08/2020
25591       00004        1E7               1433.8       15/05/2019
370318      00004        1E7               1435.3       18/02/2020
224509      00004        1E7               1434.6       25/09/2019
800938      00004        1E8                 1434       01/03/2021
664009      00004        1E8               1433.7       04/08/2020
25595       00004        1E8               1433.2       15/05/2019
370322      00004        1E8               1434.4       18/02/2020
224513      00004        1E8               1433.8       25/09/2019
800939      00004        1E9                 1435       01/03/2021
664010      00004        1E9               1433.6       04/08/2020
25596       00004        1E9               1434.6       15/05/2019
370323      00004        1E9               1435.1       18/02/2020
224514      00004        1E9               1433.4       25/09/2019
800930      00004        1F1               1360.5       01/03/2021
664001      00004        1F1               1361.7       04/08/2020
25587       00004        1F1               1362.3       15/05/2019
370314      00004        1F1               1363.7       18/02/2020
224505      00004        1F1               1365.3       25/09/2019
800929      00004        1G1                   74       01/03/2021
664000      00004        1G1                 75.9       04/08/2020
25586       00004        1G1                 75.4       15/05/2019
370313      00004        1G1                 73.9       18/02/2020
224504      00004        1G1                 72.6       25/09/2019
800928      00004        1J1                    0       01/03/2021
663999      00004        1J1                    3       04/08/2020
25585       00004        1J1                    2       15/05/2019
370312      00004        1J1                    0       18/02/2020
224503      00004        1J1                    2       25/09/2019
800968      00004         1K                    5       01/03/2021
664044      00004         1K                    7       04/08/2020
25630       00004         1K                    8       15/05/2019
370353      00004         1K                    7       18/02/2020
224544      00004         1K                    7       25/09/2019
800969      00004         1L                   OK       01/03/2021
664045      00004         1L                   OK       04/08/2020
25631       00004         1L                   OK       15/05/2019
370354      00004         1L                   OK       18/02/2020
224545      00004         1L                   OK       25/09/2019
800970      00004         1S                   OK       01/03/2021
664046      00004         1S                   OK       04/08/2020
25632       00004         1S                   OK       15/05/2019
370355      00004         1S                   OK       18/02/2020
224546      00004         1S                   OK       25/09/2019
800940      00004        1T1                  0.5       01/03/2021
664011      00004        1T1                 -7.3       04/08/2020
25597       00004        1T1                 -2.5       15/05/2019
370324      00004        1T1                 -2.3       18/02/2020
224515      00004        1T1                  7.7       25/09/2019
800941      00004        1T2                   -1       01/03/2021
664012      00004        1T2                 -8.1       04/08/2020
25598       00004        1T2                 -2.7       15/05/2019
370325      00004        1T2                 -3.7       18/02/2020
224516      00004        1T2                  6.7       25/09/2019

In [35]:
df_filtered['Date de contrôle'] = pd.to_datetime(df_filtered['Date de contrôle'], dayfirst=True)

# Trim leading and trailing spaces in 'No. Ident.' and 'Quote_name'
df_filtered['No. Ident.'] = df_filtered['No. Ident.'].str.strip()
df_filtered['Quote_name'] = df_filtered['Quote_name'].str.strip()

df_sorted = df_filtered.sort_values(by=['No. Ident.', 'Quote_name', 'Date de contrôle'])


df_sorted[['No. Ident.', 'Quote_name','Quote_measured_value', 'Date de contrôle']].head(100)

       No. Ident. Quote_name Quote_measured_value Date de contrôle
25593       00004         1B               1393.1       2019-05-15
224511      00004         1B               1392.2       2019-09-25
370320      00004         1B               1392.5       2020-02-18
664007      00004         1B               1392.4       2020-08-04
800936      00004         1B               1393.5       2021-03-01
25592       00004         1C                 38.4       2019-05-15
224510      00004         1C                 39.7       2019-09-25
370319      00004         1C                 39.6       2020-02-18
664006      00004         1C                 39.1       2020-08-04
800935      00004         1C                 38.5       2021-03-01
25594       00004         1D               1347.9       2019-05-15
224512      00004         1D               1346.8       2019-09-25
370321      00004         1D               1347.2       2020-02-18
664008      00004         1D               1347.3       2020-08-04
800937      00004         1D               1348.5       2021-03-01
25582       00004        1E1               1435.2       2019-05-15
224500      00004        1E1               1436.2       2019-09-25
370309      00004        1E1               1435.7       2020-02-18
663996      00004        1E1               1435.7       2020-08-04
800925      00004        1E1               1435.5       2021-03-01
25583       00004        1E2                 1436       2019-05-15
224501      00004        1E2                 1437       2019-09-25
370310      00004        1E2               1437.6       2020-02-18
663997      00004        1E2               1437.3       2020-08-04
800926      00004        1E2               1436.5       2021-03-01
25584       00004        1E3               1435.7       2019-05-15
224502      00004        1E3               1435.9       2019-09-25
370311      00004        1E3               1437.6       2020-02-18
663998      00004        1E3               1434.6       2020-08-04
800927      00004        1E3               1434.5       2021-03-01
25588       00004        1E4               1437.2       2019-05-15
224506      00004        1E4                 1438       2019-09-25
370315      00004        1E4               1438.7       2020-02-18
664002      00004        1E4               1437.8       2020-08-04
800931      00004        1E4                 1435       2021-03-01
25589       00004        1E5               1434.5       2019-05-15
224507      00004        1E5               1434.5       2019-09-25
370316      00004        1E5               1435.3       2020-02-18
664003      00004        1E5               1434.6       2020-08-04
800932      00004        1E5                 1435       2021-03-01
25590       00004        1E6               1433.1       2019-05-15
224508      00004        1E6               1433.7       2019-09-25
370317      00004        1E6               1434.6       2020-02-18
664004      00004        1E6               1433.2       2020-08-04
800933      00004        1E6                 1434       2021-03-01
25591       00004        1E7               1433.8       2019-05-15
224509      00004        1E7               1434.6       2019-09-25
370318      00004        1E7               1435.3       2020-02-18
664005      00004        1E7               1433.2       2020-08-04
800934      00004        1E7                 1433       2021-03-01
25595       00004        1E8               1433.2       2019-05-15
224513      00004        1E8               1433.8       2019-09-25
370322      00004        1E8               1434.4       2020-02-18
664009      00004        1E8               1433.7       2020-08-04
800938      00004        1E8                 1434       2021-03-01
25596       00004        1E9               1434.6       2019-05-15
224514      00004        1E9               1433.4       2019-09-25
370323      00004        1E9               1435.1       2020-02-18
664010      00004        1E9               1433.6       2020-08-04
800939      00004        1E9                 1435       2021-03-01
25587       00004        1F1               1362.3       2019-05-15
224505      00004        1F1               1365.3       2019-09-25
370314      00004        1F1               1363.7       2020-02-18
664001      00004        1F1               1361.7       2020-08-04
800930      00004        1F1               1360.5       2021-03-01
25586       00004        1G1                 75.4       2019-05-15
224504      00004        1G1                 72.6       2019-09-25
370313      00004        1G1                 73.9       2020-02-18
664000      00004        1G1                 75.9       2020-08-04
800929      00004        1G1                   74       2021-03-01
25585       00004        1J1                    2       2019-05-15
224503      00004        1J1                    2       2019-09-25
370312      00004        1J1                    0       2020-02-18
663999      00004        1J1                    3       2020-08-04
800928      00004        1J1                    0       2021-03-01
25630       00004         1K                    8       2019-05-15
224544      00004         1K                    7       2019-09-25
370353      00004         1K                    7       2020-02-18
664044      00004         1K                    7       2020-08-04
800968      00004         1K                    5       2021-03-01
25631       00004         1L                   OK       2019-05-15
224545      00004         1L                   OK       2019-09-25
370354      00004         1L                   OK       2020-02-18
664045      00004         1L                   OK       2020-08-04
800969      00004         1L                   OK       2021-03-01
25632       00004         1S                   OK       2019-05-15
224546      00004         1S                   OK       2019-09-25
370355      00004         1S                   OK       2020-02-18
664046      00004         1S                   OK       2020-08-04
800970      00004         1S                   OK       2021-03-01
25597       00004        1T1                 -2.5       2019-05-15
224515      00004        1T1                  7.7       2019-09-25
370324      00004        1T1                 -2.3       2020-02-18
664011      00004        1T1                 -7.3       2020-08-04
800940      00004        1T1                  0.5       2021-03-01
25598       00004        1T2                 -2.7       2019-05-15
224516      00004        1T2                  6.7       2019-09-25
370325      00004        1T2                 -3.7       2020-02-18
664012      00004        1T2                 -8.1       2020-08-04
800941      00004        1T2                   -1       2021-03-01

In [36]:
df_sorted['Quote_measured_value'].dtype

dtype('O')

In [37]:
df_sorted['Quote_measured_value'] = pd.to_numeric(df_sorted['Quote_measured_value'], errors='coerce')

25593      1393.1
224511     1392.2
370320     1392.5
664007     1392.4
800936     1393.5
            ...
1111528       1.0
748822       14.5
1111529      19.5
748823       14.0
1111530      24.0
Name: Quote_measured_value, Length: 1941528, dtype: float64